### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by KiwiHawk** [jodokus31/seablock-specific#1]
![image](https://user-images.githubusercontent.com/59639/157634732-73de747f-31cc-44f0-a41c-fbaeb1db1b2b.png)

Mod list:
- Sea Block Pack mod and dependencies
- Sea Block Evil Mode and dependencies

**Comment by KiwiHawk** [comment]
Maybe use something like this?
```lua
    icons = angelsmods.functions.create_gas_recipe_icon(
      {
        "steam"
      },
      "WsWsWs",
      {
        "gas-oxygen",
        "gas-hydrogen"
      }
    ),
```

**Comment by jodokus31** [comment]
Thanks for the info, I will look into it asap
