### ISSUE TITLE
Error while trying to craft effectivity-module-3=10

### ISSUE THREAD

**Issue by bajspunk** [jodokus31/seablock-specific#2]
As the title reads.
I had 9 EM-3 already in my inventory so it tried to craft 18 EM-1, 5 EM-2 and 1 EM-3 as I could see the craft queue.
The game crashed to title screen the second it queued the crafting. I am running mostly vanilla with a new utility mods.
Game version 1.1.72 (build 60222, win64)

This is the error message I got.

The mod Idle crafter (0.0.1) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event idle-crafter::on_nth_tick(30)
idle-crafter/control.lua:260: attempt to index global 'recipe' (a nil value)
stack traceback:
idle-crafter/control.lua:260: in function 'check_player'
idle-crafter/control.lua:299: in function <idle-crafter/control.lua:297>

**Comment by jodokus31** [comment]
Thanks for the report. I'll look into it.

**Comment by jodokus31** [comment]
I wonder, if this error is reproducible. I don't manage to do so.

But I made a mistake to use a global variable "recipe", I should use a local variable instead.
As of now, it can theoretically happen, that another mod changes the global "recipe" the moment I want to access it, and then *boom*

So, I guess, I will try to fix that and the issue will be hopefully gone...

**Comment by jodokus31** [comment]
Ok, I released the fix
